# Generated by Django 3.1.7 on 2021-04-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210417_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='nice_name',
        ),
    ]
