# Generated by Django 3.1.7 on 2021-04-19 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_recipe_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='in_list',
            field=models.ManyToManyField(blank=True, default='', related_name='listed_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
