# Generated by Django 3.2 on 2021-04-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20210428_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
